### ISSUE TITLE
关于路径积分

### ISSUE THREAD

**Issue by holycitysimplelove** [CarlDegio/PI2-DMPs#2]
最近在看路径积分和DMP结合相关的论文，看得很迷糊，想来请教下。DMP，在固定起点和终点的情况下，即使受到噪声干扰，也能正常从起点出发，然后顺利到达终点。这里应用强化学习的目的，是为了让受到干扰的轨迹更加贴近无干扰时的轨迹吗？我刚开始学习，研究您的代码有几天了，试图扩展到多维一直没有成功，方便向您请教一下吗 谢谢。

**Comment by CarlDegio** [comment]
DMP方法是用来表示轨迹的，可以使用最小二乘算出其中非线性部分的**权重**来拟合任意轨迹。policy improvement+path integral（PI2）则是使用强化学习强化学习的方法，改变**权重**以使奖励最大化（或cost最小化）。所以使用强化学习的目的是和奖励相关的，只要将你想要的行为编码到奖励里就可以（如viapoint，关于一个期望经过点的大惩罚，就可以使优化后轨迹尽量经过期望点）。扩展多维方面，有一个n_dmps的变量，决定了轨迹中包含的维数（每一个维度都是一个状态-时间轨迹）。可以加QQ2536890272细说
