### ISSUE TITLE
关于DMP中alpha_x的值的设置

### ISSUE THREAD

**Issue by lsde228** [CarlDegio/PI2-DMPs#3]
你好，我在跑你代码的过程中发现你dmp系统中 alpha_x 的值设置为8，这样跑的时候 xt 的值并不能随指数从1衰减到0，请问这样设置有什么用途吗？

**Comment by CarlDegio** [comment]
x_t并不要求要到0，alpha_x的作用是改变每个基函数的分布中心，目前感觉这个参数对算法效果影响不太大，可能只是会影响一些数值问题。我这个参数参照的是matlab代码
