### ISSUE TITLE
length和dmp_length区别？

### ISSUE THREAD

**Issue by lsde228** [CarlDegio/PI2-DMPs#4]
你好 我最近在学习你的代码，有一个地方不太懂，想请教一下，我看到在DMPOptions中设置了两个时间，这两个时间对PI2和DMP有什么作用和影响吗？谢谢

**Comment by CarlDegio** [comment]
length是对吸引子系统的时间，dmp_length是dmp项作用的时间。比如一个吸引子系统可以在0~5s运行，但只有1~3s内有dmp项（非线性项）

**Comment by lsde228** [comment]
明白了谢谢，现在的PI2轨迹实现的只是从起始点到终点吗？可不可以实现轨迹模仿呢？比如sin图像，是不是需要重新定义cost_function？

**Comment by CarlDegio** [comment]
起点到终点固定这个性质其实是吸引子系统导致的，但非线性项可以改变中间过程的形态。中间的轨迹模仿可以直接通过DMP实现（类似最小二乘的拟合），也可以通过PI2的cost实现，不过cost能做的事比轨迹模仿更广一些，如任务学习等

**Comment by ljx912912** [comment]
哥 可以加你微信或者QQ吗想向你请教一些关于dmp和pi2算法相关的事情

**Comment by ljx912912** [comment]
有偿
